server:
    port: 6060
    context-path: /design

spring:
    http:
        multipart:
          enabled: true
          file-size-threshold: 0
          max-file-size: 50MB
    profiles:
      active: @environment@

logging:
    level:
        com.boot.integration.mapper: debug

mybatis:
    type-aliases-package: com.boot.integration.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.boot.integration.util.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

security:
  oauth2:
    resource:
      filter-order: 3
